In [1]:
from applicability_domain import ApplicabilityDomain

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
boston = load_boston()
X = pd.DataFrame(boston['data'], columns = boston['feature_names'])
y = pd.Series(boston['target'], name = 'PRICE')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 334)

In [3]:
AD = ApplicabilityDomain(k = 5, alpha = 0.9)

boolean_train, boolean_test = AD.is_inside(X_train, X_test)
boolean_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [4]:
boolean_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [5]:
boolean_test

array([ True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True, False, False,  True,
       False,  True, False])

In [6]:
rd_train, rd_test = AD.get_ratio_distance(X_train, X_test)

In [7]:
rd_train

array([0.62315508, 0.94059519, 0.31742562, 0.49192105, 0.58453019,
       0.63904343, 0.59455812, 0.60225135, 0.45817228, 0.652712  ,
       0.45834776, 0.64066032, 0.63309638, 0.49294828, 0.60799457,
       1.43854939, 0.2923563 , 0.45186202, 0.65277755, 0.51015006,
       0.77547809, 1.33503381, 0.64475097, 0.64265034, 1.26636097,
       1.390723  , 0.37715221, 0.97222753, 0.85410093, 0.58565412,
       0.3228659 , 0.42109022, 0.29095446, 0.52703988, 0.59846777,
       0.61294091, 0.43455909, 0.29555491, 0.62882974, 0.69463586,
       0.58971798, 0.9488652 , 0.69078034, 0.41820941, 0.75771612,
       0.52478767, 0.51529609, 0.66687105, 0.2806634 , 0.41266949,
       0.52399976, 0.52294133, 0.64931266, 0.35794588, 0.77645054,
       1.19745587, 0.51258141, 0.6882776 , 0.41763217, 0.66581116,
       0.33928924, 0.47398375, 0.31255369, 0.38803055, 0.90614569,
       0.76980572, 0.4825028 , 1.07037772, 1.47630568, 0.85438574,
       0.41894713, 1.71768931, 0.61663874, 0.79842779, 2.02186

In [8]:
rd_test

array([0.67270132, 0.63238405, 0.80701968, 1.07999036, 0.72298805,
       0.56994203, 1.06172834, 0.37703527, 1.46566559, 0.81219129,
       0.69213884, 0.83758606, 0.80334288, 1.42601727, 1.02896106,
       0.6909648 , 0.71314929, 0.46906575, 1.46322346, 0.98194221,
       0.79274952, 0.72787545, 0.7035792 , 0.69680172, 0.49267627,
       0.60405839, 0.38795775, 0.92824911, 0.32621051, 0.60257517,
       1.15942699, 1.08337745, 0.75919968, 0.5597097 , 0.62127226,
       0.50344194, 0.78546588, 0.92211309, 0.81225198, 0.47610945,
       0.38845792, 1.15263062, 0.71396021, 1.56334385, 0.3592316 ,
       0.83381068, 1.8831938 , 0.51324254, 1.07978455, 0.76495478,
       0.99365352, 0.60828437, 0.69932478, 0.64610152, 0.76109175,
       0.79033218, 0.78990057, 0.75195267, 1.08239912, 0.85637134,
       0.49883799, 0.85359188, 0.67048375, 0.85432566, 0.55708414,
       0.79040952, 0.79563948, 0.38411694, 0.90966768, 0.62165709,
       0.71880028, 0.63468694, 0.68945655, 0.91148401, 1.00121

In [9]:
np.all((rd_train <= 1) == boolean_train)

True

In [10]:
np.all((rd_test <= 1) == boolean_test)

True